# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: build and test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x
      
    - name: Set up Docker
      uses: docker/setup-docker@v2
      with:
        docker-version: 'latest'  # You can specify your desired Docker version    
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
      working-directory: src/FlureeDotnetLibrary/FlureeDotnetLibrary.csproj
    - name: Test
      run: dotnet test --configuration Release --no-build
      working-directory: src/FlureeDotnetLibrary/FlureeDotnetLibrary.csproj
