name: publish to nuget
on:
  push:
    branches:
      - main # Default release branch
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x
    
    - name: Install dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Package
      run: dotnet pack -c Release -o . src/FlureeDotnetLibrary/FlureeDotnetLibrary.csproj
    
    - name: Publish
      run: dotnet nuget push *.nupkg -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate

    - name: Extract NuGet Package Version
      id: extract-version
      run: echo "::set-output name=package-version::$(dotnet nuget list source/FlureeDotnetLibrary.*.nupkg --include-prerelease --outdated | cut -d ' ' -f 2)"
    
    - name: Create GitHub Tag
      run: |
        TAG_NAME=${{ steps.extract-version.outputs.package-version }}
        git tag $TAG_NAME
        git push origin $TAG_NAME
